# Generated by Django 4.2.7 on 2023-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_problemissuereport_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
