name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        python -m spacy download en_core_web_sm

    - name: Clone physics_solver
      uses: actions/checkout@master
      with:
        repository: InAnYan/physics_solver
        path: lib/

    - name: Install physics_solver
      run: |
        cd lib
        pip install -r requirements.txt
        pip install .
        cd ..
   
    - name: Run Tests
      run: |
        pwd
        ls
        python manage.py test
